

// define ioctl code
#define ASUS_SCALER_IOC_TYPE    0xc1
#define ASUS_SCALER_FW_UPDATE  _IOWR(ASUS_SCALER_IOC_TYPE,	1,	int)
#define ASUS_SCALER_GET_FW_VERSION  _IOWR(ASUS_SCALER_IOC_TYPE,	2,	int)
#define ASUS_SCALER_CHECK_I2C_STABILITY  _IOWR(ASUS_SCALER_IOC_TYPE, 3,	int)
#define ASUS_SCALER_MAX_NR  3

#define ASUS_SCALER_I2C_IS_NOT_STABLE	0
#define ASUS_SCALER_I2C_IS_STABLE	1
